---
title: "p8105_HW2_rat2134"
author: "Robert Tumasian"
date: "9/28/2019"
output: github_document
---

```{r setup, include=FALSE}
#Load required packages
library(readxl)
library(janitor)
library(tidyverse)
library(dplyr)
```

# Problem 1
```{r}
#Import Mr. Trash Wheel dataset 
Mr_Trash_Data = 
  read_excel("./HW2_datasets/Mr_Trash_Wheel.xlsx",
             range = cell_cols("A:N")) %>%
  drop_na() %>%
  janitor::clean_names() %>%
  mutate(sports_balls = as.integer(
    round(sports_balls, 
          digits = 0)))
```

```{r}
#Import and clean precipitation data for 2017 and 2018
Precipitation_data_2017 =
  read_excel("./HW2_datasets/Mr_Trash_Wheel.xlsx",
             sheet = 4,
             cell_rows(3:14),
             col_names = c("Month", "Total_Precipitation")) %>%
  mutate(Year = 2017)

Precipitation_data_2018 =
  read_excel("./HW2_datasets/Mr_Trash_Wheel.xlsx",
             sheet = 3,
             cell_rows(3:9),
             col_names = c("Month", "Total_Precipitation")) %>%
  mutate(Year = 2018)

#Combine data sets
Precipitation_data_2017_and_2018 = 
  bind_rows(Precipitation_data_2017, Precipitation_data_2018) %>%
  mutate(Month = month.name[Month])
```

